name : Dylan Jager-Kujawa
description :
keyword :
url : http://www.jager-kujawa.com/
email : dylan@jager-kujawa.com
github : Kujawadl
author : Dylan Jager-Kujawa
year : 2017
markdown : kramdown
exclude :
  - node_modules

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
